# Generated by Django 5.0.2 on 2024-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickbuck_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
